//
//  DefaultExercises.swift
//  Muscle Volume
//
//  Created by Babak Kiaie on 1/6/24.
//

import Foundation
let defaultExercises = [
    Exercise(name: "Bench Press", primaryMuscle: .chest, secondaryMuscle: .triceps),
    Exercise(name: "Squat", primaryMuscle: .quadriceps, secondaryMuscle: .glutes),
    Exercise(name: "Deadlift", primaryMuscle: .back, secondaryMuscle: .hamstrings),
    Exercise(name: "Shoulder Press", primaryMuscle: .shoulders, secondaryMuscle: .triceps),
    Exercise(name: "Pull-Up", primaryMuscle: .back, secondaryMuscle: .biceps),
    Exercise(name: "Bent Over Row", primaryMuscle: .back, secondaryMuscle: .biceps),
    Exercise(name: "Leg Press", primaryMuscle: .quadriceps, secondaryMuscle: .calves),
    Exercise(name: "Lunges", primaryMuscle: .quadriceps, secondaryMuscle: .glutes),
    Exercise(name: "Leg Curl", primaryMuscle: .hamstrings, secondaryMuscle: nil),
    Exercise(name: "Calf Raise", primaryMuscle: .calves, secondaryMuscle: nil),
    Exercise(name: "Bicep Curl", primaryMuscle: .biceps, secondaryMuscle: nil),
    Exercise(name: "Tricep Extension", primaryMuscle: .triceps, secondaryMuscle: nil),
    Exercise(name: "Lat Pulldown", primaryMuscle: .back, secondaryMuscle: .biceps),
    Exercise(name: "Flyes", primaryMuscle: .chest, secondaryMuscle: nil),
    Exercise(name: "Dumbbell Row", primaryMuscle: .back, secondaryMuscle: .biceps),
    Exercise(name: "Dips", primaryMuscle: .chest, secondaryMuscle: .triceps),
    Exercise(name: "Crunches", primaryMuscle: .abs, secondaryMuscle: nil),
    Exercise(name: "Plank", primaryMuscle: .abs, secondaryMuscle: nil),
    Exercise(name: "Leg Raise", primaryMuscle: .abs, secondaryMuscle: .hipFlexors),
    Exercise(name: "Russian Twist", primaryMuscle: .abs, secondaryMuscle: .obliques),
    Exercise(name: "Push-Up", primaryMuscle: .chest, secondaryMuscle: .triceps),
    Exercise(name: "Mountain Climber", primaryMuscle: .abs, secondaryMuscle: nil),
    Exercise(name: "Burpee", primaryMuscle: .fullBody, secondaryMuscle: nil),
    Exercise(name: "Box Jump", primaryMuscle: .legs, secondaryMuscle: nil),
    Exercise(name: "Kettlebell Swing", primaryMuscle: .glutes, secondaryMuscle: .back),
    Exercise(name: "Thruster", primaryMuscle: .quadriceps, secondaryMuscle: .shoulders),
    Exercise(name: "Wall Sit", primaryMuscle: .quadriceps, secondaryMuscle: nil),
    Exercise(name: "Skull Crusher", primaryMuscle: .triceps, secondaryMuscle: nil),
    Exercise(name: "Hammer Curl", primaryMuscle: .biceps, secondaryMuscle: nil),
    Exercise(name: "T-Bar Row", primaryMuscle: .back, secondaryMuscle: .biceps),
    Exercise(name: "Face Pull", primaryMuscle: .shoulders, secondaryMuscle: .upperBack),
    Exercise(name: "Pec Deck", primaryMuscle: .chest, secondaryMuscle: nil),
    Exercise(name: "Hip Thrust", primaryMuscle: .glutes, secondaryMuscle: .hamstrings),
    Exercise(name: "Lateral Raise", primaryMuscle: .shoulders, secondaryMuscle: nil),
    Exercise(name: "Rear Delt Fly", primaryMuscle: .shoulders, secondaryMuscle: .upperBack),
    Exercise(name: "Hack Squat", primaryMuscle: .quadriceps, secondaryMuscle: .glutes),
    Exercise(name: "Seated Leg Curl", primaryMuscle: .hamstrings, secondaryMuscle: nil),
    Exercise(name: "Standing Calf Raise", primaryMuscle: .calves, secondaryMuscle: nil),
    Exercise(name: "Reverse Fly", primaryMuscle: .upperBack, secondaryMuscle: .shoulders),
    Exercise(name: "Front Squat", primaryMuscle: .quadriceps, secondaryMuscle: .glutes),
    Exercise(name: "Sumo Deadlift", primaryMuscle: .glutes, secondaryMuscle: nil),
    Exercise(name: "Barbell Curl", primaryMuscle: .biceps, secondaryMuscle: nil),
    Exercise(name: "Overhead Tricep Extension", primaryMuscle: .triceps, secondaryMuscle: nil),
    Exercise(name: "Goblet Squat", primaryMuscle: .quadriceps, secondaryMuscle: .glutes),
    Exercise(name: "Single-Arm Dumbbell Row", primaryMuscle: .back, secondaryMuscle: .biceps),
    Exercise(name: "Arnold Press", primaryMuscle: .shoulders, secondaryMuscle: .triceps),
    Exercise(name: "Cable Cross", primaryMuscle: .chest, secondaryMuscle: nil),
    Exercise(name: "Glute Bridge", primaryMuscle: .glutes, secondaryMuscle: .hamstrings),
    Exercise(name: "Shrug", primaryMuscle: .upperBack, secondaryMuscle: .shoulders),
    Exercise(name: "Incline Bench Press", primaryMuscle: .chest, secondaryMuscle: .shoulders),
    Exercise(name: "Decline Bench Press", primaryMuscle: .chest, secondaryMuscle: .triceps),
    Exercise(name: "Zottman Curl", primaryMuscle: .biceps, secondaryMuscle: nil),
    Exercise(name: "Split Squat", primaryMuscle: .quadriceps, secondaryMuscle: .glutes),
    Exercise(name: "Romanian Deadlift", primaryMuscle: .hamstrings, secondaryMuscle: .back),
    Exercise(name: "Seated Row", primaryMuscle: .back, secondaryMuscle: .biceps),
    Exercise(name: "Preacher Curl", primaryMuscle: .biceps, secondaryMuscle: nil),
    Exercise(name: "Close-Grip Bench Press", primaryMuscle: .triceps, secondaryMuscle: .chest),
    Exercise(name: "Farmer's Walk", primaryMuscle: .fullBody, secondaryMuscle: nil),
    Exercise(name: "Turkish Get-Up", primaryMuscle: .fullBody, secondaryMuscle: nil),
    Exercise(name: "Battle Rope", primaryMuscle: .arms, secondaryMuscle: .shoulders),
    Exercise(name: "Chin-Up", primaryMuscle: .back, secondaryMuscle: .biceps)
]
